name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  check_for_changes:
    runs-on: ubuntu-latest

    outputs:
      should_run: ${{ steps.check_tag.outputs.has_changed }}
      color: ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check nightly_release tag
      id: check_tag
      shell: pwsh
      run: |
        $hasChanged = ($true).ToString().ToLower()
        echo "has_changed=x$hasChanged"
        echo "has_changed=x$hasChanged" >> $GITHUB_OUTPUT

    - name: Set color
      id: random-color-generator
      shell: pwsh
      run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT

    - name: Get color
      run: |
        echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
        echo "Has changed ${{ steps.check_tag.outputs.has_changed }}"

  test:
    needs: check_for_changes
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        echo "Test ${{ needs.check_for_changes.outputs.should_run }}"
        echo "Test ${{ needs.check_for_changes.outputs.color }}"

  job1:
    name: 'Test Name'
    uses: ./.github/workflows/shared.yml
    
  job3:
    uses: ./.github/workflows/shared.yml
    with:
      is-foo: true
  
  job2:
    runs-on: ubuntu-latest
    needs: [job1, job3]
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
      - run: echo ${{ needs.job1.outputs.my-version }}
      - run: echo ${{ needs.job1.outputs.my-version2 }}
      - run: echo ${{ needs.job3.outputs.my-version }}
      - run: echo ${{ needs.job3.outputs.my-version2 }}
      


