name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    uses: ${{ github.repository }}/.github/workflows/shared.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
      - run: echo ${{ needs.job1.outputs.my-version }}

