name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    uses: Keboo/ActionsTest/.github/workflows/shared.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
      - run: echo ${{ env.my_version }}

